[package]
name = "si7021_hal"
version = "0.1.0"
authors = ["Johannes Krampf <johannes.krampf@googlemail.com>"]
edition = "2018"

[dependencies]
embedded-hal = "0.2"

[dependencies.byteorder]
default-features = false
version = "1"

